name: Deploy to Google Play Closed Testing

on:
  push:
    branches:
      - 'release/*'

jobs:
  lint:
    uses: ./.github/workflows/job_lint.yml

  unit_test:
    uses: ./.github/workflows/job_test_debug.yml

  deploy-to-google-play:
    runs-on: ubuntu-latest
    needs: [ unit_test, lint ]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      - name: set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'
          cache: gradle

      # Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build the local.properties
      - name: Set up local.properties
        run: echo "AES_KEY=${{ secrets.AES_KEY }}" > local.properties

      # Build the Android AAB (or APK if preferred)
      - name: Build Android AAB
        run: ./gradlew :composeApp:bundleLiveRelease

      # Sign KeyStore
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: composeApp/build/outputs/bundle/LiveRelease
          signingKeyBase64: ${{ secrets.SIGNING_KEYSTORE }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      # Upload AAB to Google Play Internal Testing (Internal track)
      - name: Deploy to Google Play Internal Testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.mrfatworm.zzzarchive
          releaseFiles: composeApp/build/outputs/bundle/LiveRelease/composeApp-Live-release.aab
          track: internal
          whatsNewDirectory: whatsNew/
          status: completed