name: On Push and PR

on:
  push:
    branches-ignore:
      - "doc/**"
      - 'release/**'

    paths-ignore:
      - "**/*.md"

  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/job_lint.yml

  unit_test:
    uses: ./.github/workflows/job_test_debug.yml