name: On Push and PR

on:
  push:
    branches:
      - main
      - dev

    paths-ignore:
      - '**.md'
      - "**/*.md"

  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/job_lint.yml

  unit_test:
    uses: ./.github/workflows/job_test_debug.yml